server.port: 8081

spring:
  application:
    name: enquiry-service

  datasource:
    url: jdbc:h2:mem:testDb
    username: test1
    password: test1
    
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true