spring:
  application:
    name: conversion-service
  boot:
    admin:
      client:
        url:
        - http://localhost:8888
  zipkin:
    base-url: http://localhost:9411
  main:
    allow-bean-definition-overriding: true
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'