server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  boot:
    admin:
      client:
        url: 
        - http://localhost:8888
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka   
  instance:
    prefer-ip-address: true   
    